import React, { useState } from "react";
import "../css/documents.css";

const PayoutDoc = () => {
  const [activeSection, setActiveSection] = useState("payout-request");

  // Download PDF function for individual sections
  const downloadSectionAsPDF = async (sectionId, sectionTitle) => {
    try {
      // Dynamically import the libraries
      const { jsPDF } = await import("jspdf");
      const html2canvas = await import("html2canvas");

      // Get the content element for the specific section
      const element = document.getElementById(`section-${sectionId}`);

      if (!element) {
        console.error("Section element not found");
        return;
      }

      // Show loading state
      //   const originalContent = element.innerHTML;
      //   element.innerHTML = '<div style="padding: 2rem; text-align: center;">Generating PDF... Please wait</div>';

      const canvas = await html2canvas.default(element, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
        backgroundColor: "#ffffff",
      });

      // Restore original content
      //   element.innerHTML = originalContent;

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save(`spay-${sectionId}-documentation.pdf`);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Error generating PDF. Please try again.");
    }
  };

  const apiSections = [
    {
      id: "payout-request",
      title: "Create Payout Payment Request",
      endpoint: "POST https://live.spay.live/api/bb/payout/payment/request",
      headers: "Content-Type: application/json",
      parameters: [
        {
          field: "token",
          type: "String",
          required: "Yes",
          description: "API key/token provided by Spay",
        },
        {
          field: "apitxnid",
          type: "String",
          required: "Yes",
          description:
            "	Unique transaction ID generated by the merchant (max 20 characters)",
        },

        {
          field: "bene_name",
          type: "String",
          required: "Yes",
          description: "	Beneficiary account holder's full name",
        },
        {
          field: "email",
          type: "String",
          required: "Yes",
          description: "Customer's email address",
        },
        {
          field: "mobile",
          type: "String",
          required: "Yes",
          description: "Customer's 10-digit mobile number",
        },
        {
          field: "amount",
          type: "String",
          required: "Yes",
          description: "Payout amount in INR",
        },
        {
          field: "account_number",
          type: "String",
          required: "Yes",
          description: "Beneficiary's bank account number",
        },
        {
          field: "ifsc_code",
          type: "String",
          required: "Yes",
          description: "Beneficiary's bank IFSC code",
        },
        {
          field: "mode",
          type: "String",
          required: "Yes",
          description: "Transfer mode — one of: NEFT, IMPS, FT and RTGS",
        },
      ],
      request: {
        curl: [
          "curl --location ' https://live.spay.live/api/bb/payout/payment/request'",
          "--form 'token=Q9xRwseKPXXXXXXseUtygT78wnHPji'",
          "--form 'apitxnid=TXNXXXX1120'",
          "--form 'email=customer@enduser.com'",
          "--form 'mobile=9876543210'",
          "--form 'amount=1'",
          "--form 'account_number=17459XXXXX'",
          "--form 'ifsc_code=KKBK00XXXXX'",
          "--form 'bene_name=customer / enduser name'",
          "--form 'mode=IMPS'",
        ].join("\n"),
      },
      successResponse: {
        json: `{
   "status : Success",
   "statuscode": "OK",
   "message": "Payout status: Success",
   "data": {
        "message": Transfer Success,
        "bene_name": name,
        "customer_account": xxxxxxx7325,
        "amount": "1",
        "client_ref_no": AK00XXXXX1,
        "txn_date": "2025-XX-1X 16:XX:49",
     }
   }`,
      },
      errorExamples: [
        {
          code: "403",
          message:
            "Your Payout account is deactivated. Please contact the administrator",
          cause: "Payout deactivated by Spay",
        },
        {
          code: "409",
          message: "Transaction ID already exists",
          cause: "Duplicate aptixnid used",
        },
        {
          code: "401",
          message: "Unauthorized",
          cause: "Invalid or expired token or Authorization header",
        },
        {
          code: "422",
          message: "Validator Error",
          cause:
            "Occurs when required fields (apitxnid, amount, name, mobile, email) are missing or invalid ",
        },
        {
          code: "500",
          message: "Internal Server Error",
          cause: "Unexpected server-side error",
        },
      ],
      type: "api",
    },
    {
      id: "payout-request-upi",
      title: "UPI Request",
      endpoint: "POST https://live.spay.live/api/bb/payout/upi/request",
      headers: "Content-Type: application/json",
      parameters: [
        {
          field: "token",
          type: "String",
          required: "Yes",
          description: "API key/token provided by Spay",
        },
        {
          field: "apitxnid",
          type: "String",
          required: "Yes",
          description:
            "	Unique transaction ID generated by the merchant (max 20 characters)",
        },
        {
          field: "mobile",
          type: "String",
          required: "Yes",
          description: "Customer's 10-digit mobile number",
        },
        {
          field: "amount",
          type: "String",
          required: "Yes",
          description: "Payout amount in INR",
        },
        {
          field: "mode",
          type: "String",
          required: "Yes",
          description: "Transfer mode — one of: UPI",
        },
        {
          field: "upi_id",
          type: "String",
          required: "Yes",
          description: "Beneficiary's UPI ID",
        },
      ],
      request: {
        curl: [
          "curl --location 'https://live.spay.live/api/bb/payout/upi/request'",
          "--form 'token=Q9xRwseKPXXXXXXseUtygT78wnHPji'",
          "--form 'apitxnid=TXNXXXX1120'",
          "--form 'mobile=9876543210'",
          "--form 'amount=1'",
          "--form 'upi_id=akXXXXXX-1@oksbi'",
          "--form 'mode=IMPS'",
        ].join("\n"),
      },
      successResponse: {
        json: `{
   "status : Success",
   "statuscode": "OK",
   "message": "UPI Payout status: Success",
   "data": {
        "message": Transaction Success, 
        "customer_account": xxxxxxx7325,
        "amount": "1",
        "rrn": 522XXXXX298,
        "txn_date": "2025-XX-1X 16:XX:49",
     }
   }`,
      },
      errorExamples: [
        {
          code: "403",
          message:
            "	Your payout account is deactivated. Please contact the administrator",
          cause: "payout deactivated by Spay",
        },

        {
          code: "401",
          message: "Unauthorized",
          cause: "Invalid or expired token or Authorization header",
        },
        {
          code: "422",
          message: "Validator Error",
          cause:
            "Occurs when required fields (apitxnid, amount, name, mobile, email) are missing or invalid ",
        },
        {
          code: "500",
          message: "Internal Server Error",
          cause: "Unexpected server-side error",
        },
      ],
      type: "api",
    },
    {
      id: "payment-status",
      title: "Check Payment Status",
      endpoint: "GET https://live.spay.live/api/bb/payout/status",
      headers: "Content-Type: multipart/form-data; boundary=",
      parameters: [
        {
          field: "token",
          type: "String",
          required: "Yes",
          description: "API key/token provided by SPay Dashboard",
        },
        {
          field: "apitxnid",
          type: "String",
          required: "Yes",
          description: "Unique ID Enter by Merchant(client_ref_no)",
        },
      ],
      request: {
        curl: [
          "curl --location 'GET https://dashboard.spay.live/api/bb/payout/status?'",
          "token=Q9xRwseKPkMWXXXXXT78wnHPji&apitxnid=AK0XXXX",
        ].join("\n"),
      },
      successResponse: {
        json: `{
          "status": "success",
          "statuscode": "200",
          "data": {
            "message": "Transaction Status Fetched",
            "transaction_id": "SPAY_TXN_987654321",
            "status": "SUCCESS",
            "amount": "1000.00",
            "rrn": "522XXXX286",
            "account_number": "xxxxxxx7325 ",
            "ifsc_code": "KKBK0XXXX",
            "timestamp": "2024-01-15T10:30:00Z"
          }
        }`,
      },
      // failedResponse: {
      //     json: `{
      //       "statuscode": "400",
      //       "data": {
      //         "status": "FAILED",
      //         "message": "Transaction Status failed",
      //         "amount": "1000.00",
      //         "rrn": "522XXXX286",
      //         "account_number": "xxxxxxx7325 ",
      //         "ifsc_code": "KKBK0XXXX",
      //       }
      //     }`,
      //   },
      errorExamples: [
        {
          code: "400",
          message: "Missing required fields: name,mobile, etc",
          cause: "Required fields are not included",
        },
        {
          code: "404",
          message: "	payout method not found",
          cause: "Incorrect or non-existent apitxnid",
        },
        {
          code: "401",
          message: "Unauthorized",
          cause: "Invalid or expired token or Authorization header",
        },
        {
          code: "500",
          message: "Internal Server Error",
          cause: "Unexpected server-side error",
        },
      ],
      errorStatus: [
        {
          code: "initiated",
          message: "	Payment has been initiated but not completed",
        },
        {
          code: "success",
          message: "Payment was completed successfully",
        },
        {
          code: "failed",
          message: "Payment failed",
        },
        {
          code: "pending",
          message: "Payment is in process and pending confirmation",
        },
      ],
      type: "api",
    },
    {
      id: "callback",
      title: "Callback Response",
      type: "callback",
      content: {
        endpoint:
          "https://api.rusanyafintech.com/api/rusanya/spay/payout/spay_callback",
        successResponse: `{
  "status": "success",
  "txnid": "SPAYXXXX0004",
  "clientxmld": "Axxxxxxx",
  "amount": "1.00",
  "UTR": "Vxxxxxxxf",
  "timestamp": "2025-XX-XX 15:27:47"
}`,
        failedResponse: `{
  "status": "failed",
  "txnid": "SPAYXXXX0004", 
  "clientxmld": "Axxxxxxx",
  "amount": "1.00",
  "UTR": "Vxxxxxxxf",
  "timestamp": "2025-XX-XX 15:27:47",
}`,
      },
    },
    {
      id: "important-notes",
      title: "Payout Integration Guidelines",
      type: "notes",
      content: [
        {
          title: "1. API Key & Credentials",
          description:
            "token, Mid, Terminal_id, IV, and Key: Ensure that these values are securely stored and never shared in public forums or repositories. These credentials are sensitive and must be treated with high security to prevent unauthorized access.",
        },
        {
          title: "2. Consistency in Identifiers",
          description:
            "apitxnid (for Payment request and UPI request API): This is the unique identifier you provide for each transaction. It should be unique for every transaction request and should not be reused. Reusing an apitxnid for multiple transactions can lead to erroneous results in the payout flow and in status checks.\n\npayment_id (for status API): This is the unique identifier returned by SPay in the callback response. Ensure that the payment_id returned by SPay in the response is used consistently when checking the status of a transaction via the /status API.",
        },
        {
          title: "3. Handling Transaction Status",
          description:
            "Pending Status: If the transaction status is marked as 'Pending,' it’s recommended to implement retry logic. Do not retry immediately. Wait at least 2-5 minutes before retrying the /payout/status API. Frequent retries without waiting may result in unnecessary server load and incorrect results.\n\nPolling & Cron Jobs: If you have high transaction volumes, consider implementing polling or using a cron job to check the transaction status periodically after the initial request. This ensures that the system remains responsive and reduces manual intervention.\n\nWebhook: If SPay provides a webhook for status updates, consider using it to get real-time notifications for transaction status changes. This will be more efficient than polling.",
        },
        {
          title: "4. Error Handling & Retry Logic",
          description:
            "Always implement proper error handling when calling the APIs. Ensure that you have logic in place to gracefully handle any errors that may arise, such as network issues or server downtime.",
        },
        {
          title: "5. Transaction Amount (INR)",
          description:
            "Ensure that the amount parameter is provided accurately in INR (Indian Rupees) and does not exceed the allowable limits specified by SPay. Double-check the transaction amounts before initiating the request.",
        },
        {
          title: "6. Customer Data Validation",
          description:
            "Always validate and sanitize customer input such as name, email, and mobile to ensure no invalid or harmful data is sent. Invalid or incomplete customer data may result in transaction failures or status errors.",
        },
        {
          title: "7. Security",
          description:
            "Always use HTTPS for secure communication to protect sensitive data like API keys, customer information, and transaction details.",
        },
        {
          title: "8. Payout Account Deactivated",
          description:
            "This means your payout account has been deactivated by Spay. Please contact support or the system administrator to reactivate your account.",
        },
      ],
    },
  ];

  const activeApi = apiSections.find((section) => section.id === activeSection);

  // Function to render different content based on type
  const renderContent = () => {
    switch (activeApi.type) {
      case "api":
        return (
          <>
            <div className="content-header">
              <div className="header-top">
                <h1>{activeApi.title}</h1>
                {/* <button 
                  onClick={() => downloadSectionAsPDF(activeApi.id, activeApi.title)}
                  className="download-pdf-btn"
                >
                  📄 Download PDF
                </button> */}
              </div>
              <br />
              <h4>
                <span
                  style={{
                    color: "green",
                    fontWeight: "700",
                    margin: "0px 0px 100px 0px",
                  }}
                >
                  ENDPOINT :
                </span>
                <br />
                <br />
                {activeApi.endpoint}
              </h4>
              <br />
              <h4>
                <span
                  style={{
                    color: "green",
                    fontWeight: "700",
                    margin: "0px 0px 100px 0px",
                  }}
                >
                  HEADERS :{" "}
                </span>
                <br />
                <br /> {activeApi.headers}
              </h4>
            </div>
            <div className="parameters-section">
              <h2>Request Body Parameters</h2>
              <table className="parameters-table">
                <thead>
                  <tr>
                    <th>Field</th>
                    <th>Type</th>
                    <th>Required</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  {activeApi.parameters.map((param, index) => (
                    <tr key={index}>
                      <td>
                        <code className="field-code">{param.field}</code>
                      </td>
                      <td>{param.type}</td>
                      <td>
                        <span
                          className={`required-badge ${
                            param.required === "Yes"
                              ? "required-yes"
                              : "required-no"
                          }`}
                        >
                          {param.required}
                        </span>
                      </td>
                      <td>{param.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="request-section">
              <h2>Sample Request</h2>
              <div className="code-block">
                <pre>{activeApi.request.curl}</pre>
              </div>
            </div>
            <div className="request-section">
              <h2>Success Response</h2>
              <div className="code-block success-code">
                <pre>{activeApi.successResponse.json}</pre>
              </div>
            </div>
            {activeApi.failedResponse && (
              <div className="request-section">
                <h2>failed Response</h2>
                <div className="code-block success-code">
                  <pre>{activeApi.failedResponse.json}</pre>
                </div>
              </div>
            )}
            {activeApi.errorExamples && (
              <div className="error-examples-section">
                <h2>Error Response Examples</h2>
                <table className="error-examples-table">
                  <thead>
                    <tr>
                      <th>Error Code</th>
                      <th>Message</th>
                      <th>Cause</th>
                    </tr>
                  </thead>
                  <tbody>
                    {activeApi.errorExamples.map((error, index) => (
                      <tr key={index}>
                        <td>
                          <code className="error-code-badge">{error.code}</code>
                        </td>
                        <td>{error.message}</td>
                        <td>{error.cause}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
            {activeApi.errorStatus && (
              <div className="error-status-section">
                <h2>status values in data.status</h2>
                <table className="error-status-table">
                  <thead>
                    <tr>
                      <th>Status</th>
                      <th>Meaning</th>
                      {/* <th>Cause</th> */}
                    </tr>
                  </thead>
                  <tbody>
                    {activeApi.errorStatus.map((error, index) => (
                      <tr key={index}>
                        <td>
                          <code className="error-status-badge">
                            {error.code}
                          </code>
                        </td>
                        <td>{error.message}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        );

      case "callback":
        return (
          <div className="content-section">
            <div className="header-top">
              <h1>
                <b>{activeApi.title}</b>
              </h1>
              {/* <button
                onClick={() =>
                  downloadSectionAsPDF(activeApi.id, activeApi.title)
                }
                className="download-pdf-btn"
              >
                📄 Download PDF
              </button> */}
            </div>

            <div className="info-box">
              <h3>User Callback Endpoint</h3>
              <div className="endpoint-block">
                <code>{activeApi.content.endpoint}</code>
              </div>
            </div>

            <div className="response-examples">
              <div className="response-example">
                <h3 style={{ color: "#10b981" }}>
                  ✅ Callback Success Response
                </h3>
                <div className="code-block success-code">
                  <pre>{activeApi.content.successResponse}</pre>
                </div>
              </div>

              <div className="response-example">
                <h3 style={{ color: "#ef4444" }}>
                  ❌ Callback Failed Response
                </h3>
                <div className="code-block error-code">
                  <pre>{activeApi.content.failedResponse}</pre>
                </div>
              </div>
            </div>
          </div>
        );

      case "notes":
        return (
          <div className="content-section">
            <div className="header-top">
              <h1>{activeApi.title}</h1>
              {/* <button 
                onClick={() => downloadSectionAsPDF(activeApi.id, activeApi.title)}
                className="download-pdf-btn"
              >
                📄 Download PDF
              </button> */}
            </div>
            <div className="guidelines-box">
              <h3>Integration Guidelines</h3>
              <div className="guidelines-list">
                {activeApi.content.map((guideline, index) => (
                  <div key={index} className="guideline-item">
                    <h4 className="guideline-title">{guideline.title}</h4>
                    <p className="guideline-description">
                      {guideline.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        );

      default:
        return (
          <div className="content-section">
            <h1>{activeApi.title}</h1>
            <p>Content for this section is being prepared.</p>
          </div>
        );
    }
  };

  return (
    <div className="api-doc-container">
      {/* Sidebar */}
      <div className="api-doc-sidebar">
        <div className="sidebar-header">
          <h2>API Documentation</h2>
        </div>
        <nav className="sidebar-nav">
          {apiSections.map((section) => (
            <div key={section.id} className="nav-item-container">
              <button
                onClick={() => setActiveSection(section.id)}
                className={`nav-item ${
                  activeSection === section.id ? "nav-item-active" : ""
                }`}
              >
                <div className="nav-title">{section.title}</div>
              </button>
              {/* <button
                onClick={() => downloadSectionAsPDF(section.id, section.title)}
                className="nav-download-btn"
                title={`Download ${section.title} as PDF`}
              >
                📥
              </button> */}
            </div>
          ))}
        </nav>
      </div>

      {/* Main Content with ID for PDF generation */}
      <div className="api-doc-content">
        <div
          id={`section-${activeSection}`}
          className="content-wrapper pdf-content"
        >
          {renderContent()}
        </div>
      </div>
    </div>
  );
};

export default PayoutDoc;
